name: flutter_w
description: A Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
 

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Notifications
  flutter_local_notifications: ^17.1.0

  # Image & Share
  image_picker: ^1.0.7
  share_plus: ^10.0.0

  # State Management
  provider: ^6.1.2
  get: ^4.6.6

  # Network
  dio: ^5.4.0
  http: ^1.5.0

  # UI
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  lottie: ^3.3.1

  # Utils
  intl: ^0.20.2
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  crypto: ^3.0.7
  async: ^2.13.0
  math_expressions: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/